name: fabric_ui_animation

description: A 3D cloth physics simulation widget for Flutter. Grab, pull, stretch, and tear the UI with dynamic lighting and Verlet integration. # 60 se 180 characters ke beech hona chahiye

version: 1.0.1

homepage: https://github.com/Jayeshkashyap2201

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0